# Generated by Django 5.1.4 on 2024-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_appointment_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
