# Generated by Django 5.1.4 on 2025-01-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctorName', 'appointmentDate', 'appointmentTime')},
        ),
    ]
