# Generated by Django 5.1.4 on 2025-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(),
        ),
    ]
